# Generated by Django 4.1.3 on 2023-01-31 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_alter_loan_customer_alter_loan_is_delayed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray', models.PositiveIntegerField(unique=True)),
                ('date_deposited', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.loan')),
            ],
        ),
    ]
