# Generated by Django 4.1.3 on 2023-01-31 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_loan_customer_alter_loan_is_delayed_and_more'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.loan', unique=True),
        ),
    ]
